
[package]
authors     = ["Golem Foundation Contributors <contact@golem.foundation>"]
description = "Wildland Cargo Lib"
edition     = "2021"
homepage    = "https://wildland.io/"
keywords    = ["storage"]
license     = "GPL-3.0-only"
name        = "wildland-cargo-lib"
publish     = ["wl-dev"]
repository  = "https://gitlab.com/wildland/corex/wildland-core"
version     = "0.10.0"


[features]
bindings = ["swift-bridge", "ffi-macro", "ffi-macro-build"]


[lib]
crate-type = ["staticlib", "lib"]


[dependencies]
anyhow             = { version = "1.0" }
env_logger         = { version = "0.9" }
ffi-macro          = { version = "0.7.1", registry = "wl-dev", optional = true }
log                = { version = "0.4" }
sha2               = { version = "0.10" }
swift-bridge       = { version = "0.1", optional = true }
thiserror          = { version = "1.0" }
tracing            = { version = "0.1" }
tracing-appender   = { version = "0.2" }
tracing-attributes = { version = "0.1" }
tracing-core       = { version = "0.1" }
tracing-log        = { version = "0.1", features = ["env_logger"] }
tracing-subscriber = { version = "0.3", features = ["json", "env-filter", "fmt", "std"] }
wildland-corex     = { version = "0.6.0", path = "../wildland-corex", registry = "wl-dev" }

[package.metadata.workspaces]
independent = true

[build-dependencies]
ffi-macro-build = { version = "0.5.2", registry = "wl-dev", optional = true }

[dev-dependencies]
hex-literal = { version = "0.3.4" }
mockall     = { version = "0.11" }
