image: rust:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  except:
    - tags
  script:
    - cargo test --verbose

lint:
  stage: test
  except:
    - tags
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

format:
  stage: test
  except:
    - tags
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check

audit:
  stage: test
  except:
    - tags
  script:
    - cargo install cargo-audit
    - cargo audit

build:
  stage: build
  except:
    - tags
  only:
    - main
    - merge_requests
  script:
    - cargo build

publish:
  stage: deploy
  except:
    - tags
  only:
    - main
  script:
    - cargo install cargo-release
    - EXCLUDES=$(diff <(cargo workspaces list) <(cargo workspaces changed) | grep '< ' | sed 's/< //' | xargs -I@ echo -n "--exclude @ ")
    - cargo release --workspace --no-verify --no-confirm --execute $EXCLUDES release
