[book]
authors = ["Golem Foundation Contributors <contact@golem.foundation>"]
language = "en"
multilingual = false
src = "docs"
<<<<<<< HEAD
title = "Wildland Medium Level Documentation"
=======
title = "Wildland documentation"
>>>>>>> origin/main

[build]
build-dir = "public/mld"
create-missing = true
use-default-preprocessors = true

<<<<<<< HEAD

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
=======
[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
>>>>>>> origin/main
curly-quotes = true
mathjax-support = false
copy-fonts = true
#additional-css = ["custom.css", "custom2.css"]
#additional-js = ["custom.js"]
no-section-label = false
#git-repository-url = "https://github.com/rust-lang/mdBook"
#git-repository-icon = "fa-github"
#edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
#site-url = "/example-book/"
#cname = "myproject.rs"
#input-404 = "not-found.md"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
<<<<<<< HEAD
line-numbers = false     # displays line numbers for editable code
=======
line-numbers = true     # displays line numbers for editable code
>>>>>>> origin/main
runnable = true          # displays a run button for rust code

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search

#[output.html]
# git-repository-url = "https://docs.wildland.dev"

#[output.linkcheck]
#warning-policy = "error"

#[preprocessor.plantuml]
