[book]
authors      = ["Golem Foundation Contributors <contact@golem.foundation>"]
language     = "en"
multilingual = false
src          = "docs"
title        = "Wildland documentation"

[build]
build-dir                 = ".docs/mld"
create-missing            = true
use-default-preprocessors = true

[output.html]
copy-fonts           = true
curly-quotes         = true
default-theme        = "dark"
mathjax-support      = false
preferred-dark-theme = "ayu"
#additional-css = ["custom.css", "custom2.css"]
#additional-js = ["custom.js"]
no-section-label = false
#git-repository-url = "https://github.com/rust-lang/mdBook"
#git-repository-icon = "fa-github"
#edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
#site-url = "/example-book/"
#cname = "myproject.rs"
#input-404 = "not-found.md"

[output.html.fold]
enable = true # whether or not to enable section folding
level  = 0    # the depth to start folding

[output.html.playground]
copy-js      = true  # includes the JavaScript for the code editor
copyable     = true  # include the copy button for copying code snippets
editable     = false # allows editing the source code
line-numbers = true  # displays line numbers for editable code
runnable     = true  # displays a run button for rust code

[output.html.search]
boost-hierarchy     = 1    # ranking boost factor for matches in page names
boost-paragraph     = 1    # ranking boost factor for matches in text
boost-title         = 2    # ranking boost factor for matches in headers
copy-js             = true # include Javascript code for search
enable              = true # enables the search feature
expand              = true # partial words will match longer terms
heading-split-level = 3    # link results to heading levels
limit-results       = 30   # maximum number of search results
teaser-word-count   = 30   # number of words used for a search result teaser
use-boolean-and     = true # multiple search terms must all match

#[output.html]
# git-repository-url = "https://docs.wildland.dev"

#[output.linkcheck]
#warning-policy = "error"

#[preprocessor.plantuml]
