[workspace]

members = [
    "wildland-admin-manager",
    "wildland-admin-manager-api",
    "wildland-catlib",
    "wildland-rust-cli",
    "wildland-corex",
    "wildland-crypto",
    "wildland-dfs",
    "wildland-wallet",
]
