[workspace]

members = [
    "wildland-admin-manager",
    "wildland-catlib",
    "wildland-cli",
    "wildland-cli-python-bindings",
    "wildland-corex",
    "wildland-dfs",
    "wildland-wallet",
]