[workspace]

members = [
    "wildland-admin-manager",
    "wildland-admin-manager-api",
    "wildland-catlib",
    "wildland-cli",
    "wildland-corex",
    "wildland-crypto",
    "wildland-storage-controller-client",
    "wildland-dfs",
    "wildland-wallet",
]
