[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.bindings-linux]
description = "Build Cargo bindings for x86_64 linux"
command = 'cargo'
args = [
	'build',
	'--package',  'wildland-cargo-lib',
	'--features', 'bindings',
	'--target',   'x86_64-unknown-linux-gnu'
]


[tasks.lld-docs]
description = 'Generate Low Level (ie. rust) Documentation for entire Wildland Core workspace'
category = 'Documentation'
command = 'cargo'
workspace = false
args = [
	'doc',
	'--target-dir', '.docs/lld',
	'--all-features',
	'--no-deps',
]
