# Tasks in this file are meant to be usable not only
# in the workspace root but in the member crates as well
#
# ie. you shouldn't have to switch from a member crate to the
# workspace root in order to run fmt or clippy
#
# This file is meant to be used as an extension to both Makefile in the
# workspace root as well as in the member crates.

[tasks.clippy]
args          = ["clippy", "--all-targets", "--", "-D", "warnings"]
command       = "cargo"
install_crate = "clippy"
toolchain     = "nightly"

[tasks.format]
args          = ["fmt"]
command       = "cargo"
install_crate = "rustfmt"
toolchain     = "nightly"

[tasks.format-check]
args          = ["fmt", "--", "--check"]
command       = "cargo"
install_crate = "rustfmt"
toolchain     = "nightly"

[tasks.clippy-fix]
args          = ['clippy', "--all-targets", "--fix", "--allow-no-vcs", "--", "-D", "warnings"]
command       = "cargo"
env           = { "__CARGO_FIX_YOLO" = "1" }
install_crate = "clippy"
toolchain     = "nightly"

[tasks.code-fix]
run_task = { name = ["clippy-fix", "format"] }

[tasks.deps-up]
args      = ["--file", "../../docker-compose.yml", "up", "--force-recreate", "--detach"]
command   = "docker-compose"
private   = false
workspace = false
