[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.clippy]
args          = ["clippy", "--all-targets", "--", "-D", "warnings"]
command       = "cargo"
install_crate = "clippy"

[tasks.format]
toolchain = "nightly"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.format-check]
toolchain = "nightly"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.bindings-linux]
args        = ['build', '--package', 'wildland-cargo-lib', '--features', 'bindings', '--target', 'x86_64-unknown-linux-gnu']
command     = 'cargo'
description = "Build Cargo bindings for x86_64 linux"


[tasks.lld-docs]
args        = ['doc', '--target-dir', '.docs/lld', '--all-features', '--no-deps']
category    = 'Documentation'
command     = 'cargo'
description = 'Generate Low Level (ie. rust) Documentation for entire Wildland Core workspace'
workspace   = false

[tasks.deny-licenses]
args		= ['deny', 'check', 'licenses']
category	= 'Checks'
command		= 'cargo'
description	= 'check OSS licenses'
workspace	= true
