allow-branch               = ['master']
consolidate-commits        = true
pre-release-commit-message = "Workspace crates release version {{prev_version}} set to {{version}}"
shared-version             = true
tag                        = true
tag-message	               = "Workspace crates release version {{prev_version}} set to {{version}}"
tag-name                   = "v{{version}}"
verify                     = false
