FROM debian:testing

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -qy update && apt-get install -y g++ cargo swig
RUN mkdir -p wildland-core/wildland-admin-manager /root/.cargo
COPY . wildland-core
WORKDIR /wildland-core/wildland-admin-manager
RUN printf '[registries]\nwl-dev = { index = "https://crates.wildland.dev/git/index" }\n' > /root/.cargo/config.toml \
    && cargo clean \
    && cargo build --features "bindings"
