[package]
name = "wildland-wallet"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-only"
description = "A Wildland keystore library"
publish = ["wl-dev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
