[package]
name = "wildland-admin-manager-api"
version = "0.1.0"
edition = "2021"
publish = ["wl-dev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
