version: '3'

#############################################
# This file is for development purposes only
#############################################

services:
  wildland-bindings-builder:
    build:
      context: ..
      dockerfile: Dockerfile.builder
    image: wildland-bindings-builder

  wildland-bindings:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.base
    image: wildland-bindings-base
