[package]
name = "wildland-http-client"
version = "0.4.3"
authors = ["Golem Foundation Contributors <contact@golem.foundation>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://gitlab.com/wildland/corex/wildland-core"
homepage = "https://wildland.io/"
description = "Wildland http client"
keywords = ["http", "client"]
publish = ["wl-dev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde            = { version = "1.0", features = ["derive"] }
serde_json       = { version = "1.0" }
reqwest          = { version = "0.11", features = ["json"] }
log              = { version = "0.4" }
thiserror        = { version = "1.0" }
tracing          = { version = "0.1" }
# currently versioning is not in best shape, thus its bound to patch
wildland-crypto  = { version = "0.6.0", path = "../wildland-crypto", registry = "wl-dev" }

[dev-dependencies]
dotenv          = { version = "0.15" }
tokio           = { version = "1.17", features = ["macros", "rt-multi-thread"] }
mockito         = { version = "0.31" }
http            = { version = "0.2" }

[package.metadata.workspaces]
independent = true
