[package]
authors     = ["Golem Foundation Contributors <contact@golem.foundation>"]
description = "A Wildland file system handler"
edition     = "2021"
homepage    = "https://wildland.io/"
keywords    = ["storage"]
license     = "GPL-3.0-only"
name        = "wildland-dfs"
publish     = ["wl-dev"]
repository  = "https://gitlab.com/wildland/corex/wildland-core"
version     = "0.30.1-rc.0"

[dependencies]
wildland-corex = { version = "0.30.1-rc.0", path = "../wildland-corex", registry = "wl-dev" }
