[package]
name = "wildland-dfs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "A Wildland file system handler"
publish = ["wl-dev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
