[package]
name = "wildland-admin-manager"
version = "0.3.0"
authors = ["Golem Foundation Contributors <contact@golem.foundation>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://gitlab.com/wildland/corex/wildland-core"
homepage = "https://wildland.io/"
description = "Wildland Admin Manager"
keywords = ["storage"]
publish = ["wl-dev"]

[lib]
crate-type = ["staticlib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wildland-corex = { version = "0.1.3-alpha.0", path = "../wildland-corex", registry = "wl-dev" }
wildland-crypto = { version = "0.4.0", path = "../wildland-crypto", registry = "wl-dev" }
wildland-admin-manager-api = { version = "0.2.0", path = "../wildland-admin-manager-api", registry = "wl-dev" }
bip39 = { version = "1.0.1", features = ["rand"] }
thiserror = "1.0.31"
cxx = "1.0"
lazy_static = "1"

[package.metadata.workspaces]
independent = true


[build-dependencies]
cxx-build = { version = "1.0" }
