[package]
name = "wildland-admin-manager"
version = "0.3.1"
authors = ["Golem Foundation Contributors <contact@golem.foundation>"]
edition = "2021"
license = "GPL-3.0-only"
repository = "https://gitlab.com/wildland/corex/wildland-core"
homepage = "https://wildland.io/"
description = "Wildland Admin Manager"
keywords = ["storage"]
publish = ["wl-dev"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wildland-corex = { version = "0.1.5", path = "../wildland-corex", registry = "wl-dev" }
wildland-admin-manager-api = { version = "0.2.0", path = "../wildland-admin-manager-api", registry = "wl-dev" }
bip39 = { version = "1.0.1", features = ["rand"] }
thiserror = "1.0.31"

[package.metadata.workspaces]
independent = true
