[package]
name = "cargo_common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"

[build-dependencies]
cxx-build = "1.0"