[package]
name = "cargo_common"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
rand_core = { version = "0.6", features = ["std"] }

# bip32 = "0.2.2"
# supports bip32, it's support for bip39 is limited to 24 words mnemonics only
# seed is 64 bytes long, derivation is strict bip32, no ed25519
# 96 bytes long BIP32 extended key

bip39 = "1.0.1"
# supports 12 words long mnemonics; seed is 64 bytes long

# Q: is bip39 crate compatible with ed25519-bip32 crate?
# A: very likely!
# Q: determine how chain_code is generated in ed25519-bip32 crate

ed25519-bip32 = "0.4.0"
# built on top of cryptoxide;
# 64 bytes long secret key
# 96 bytes long BIP32 extended key

[build-dependencies]
cxx-build = "1.0"