# rationale: https://i.imgur.com/Qv7yao8.png
#
# Extracts bump version generated by cargo workspaces
#
# Example commit message:
#     Set pre-release crates version %n
#
#     wildland-cargo-lib@0.1.0-rc.0
#     wildland-catlib@0.1.0-rc.0
#     wildland-corex@0.1.0-rc.0
#     wildland-crypto@0.1.0-rc.0
#     wildland-dfs@0.1.0-rc.0
#     wildland-http-client@0.1.0-rc.0
#
# Results in:
#   0.1.0-rc.0
#

puts [*STDIN.map(&:strip).join(':::').match(/@(\d+\.\d+\.\d+.+?):::/)].last
