[package]
authors     = ["Golem Foundation Contributors <contact@golem.foundation>"]
description = "Wildland Catalog Library client"
edition     = "2021"
homepage    = "https://wildland.io/"
keywords    = ["storage"]
license     = "GPL-3.0-only"
name        = "wildland-catlib"
publish     = ["wl-dev"]
repository  = "https://gitlab.com/wildland/corex/wildland-core"
version     = "0.30.0"

[dependencies]
derivative  = { version = "2.2" }
directories = { version = "4.0.1" }
hex         = { version = "0.4" }
serde       = { version = "1.0.144", features = ["derive"] }
serde_yaml  = { version = "0.9.11" }

tempfile       = { version = "3.3.0" }
thiserror      = { version = "1.0.35" }
tracing        = { version = "0.1" }
uuid           = { version = "1.1.2", features = ["v4", "serde"] }
wildland-corex = { version = "0.30.0", path = "../wildland-corex", registry = "wl-dev" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { version = "*" }
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = { version = "*" }
web-sys = { version = "0.3", features = [
    "console",
    "ErrorEvent",
    "RequestInit",
    "Request",
    "RequestMode",
    "Window",
    "WebSocket",
    "BinaryType",
    "Blob",
    "ErrorEvent",
    "MessageEvent",
    "TcpSocket",
] }


[dev-dependencies]
rand   = { version = "0.8.5" }
rstest = { version = "0.15.0" }
