[package]
authors     = ["Golem Foundation Contributors <contact@golem.foundation>"]
description = "Wildland Catalog Library client"
edition     = "2021"
homepage    = "https://wildland.io/"
keywords    = ["storage"]
license     = "GPL-3.0-only"
name        = "wildland-catlib"
publish     = ["wl-dev"]
repository  = "https://gitlab.com/wildland/corex/wildland-core"
version     = "0.7.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative  = { version = "2.2" }
directories = { version = "4.0.1" }
hex         = { version = "0.4" }
ron         = { version = "0.8.0" }
rustbreak   = { version = "2.0.0", features = ["serde_yaml", "ron_enc", "yaml_enc", "mmap"] }
serde       = { version = "1.0.144", features = ["derive"] }
serde_yaml  = { version = "0.9.11" }
tempfile    = { version = "3.3.0" }
thiserror   = { version = "1.0.35" }
tracing     = { version = "0.1" }
uuid        = { version = "1.1.2", features = ["v4", "serde"] }

[dev-dependencies]
mocktopus = { version = "0.7.11" }
rand      = { version = "0.8.5" }
rstest    = { version = "0.15.0" }

[package.metadata.workspaces]
independent = true
